# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0518
  location: westeurope
  environment: prod
  enable_aml_computecluster: true
  enable_monitoring: false


  # Azure DevOps
  ado_service_connection_rg: ARM-test
  ado_service_connection_aml_ws: ARM-test

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: amlarc-doris
  aml_workspace: doris0ws
  application_insights: dorisws8072145540
  key_vault: dorisws6231326050
  container_registry: f23a7c6035b940d78493a69631f1357e
  storage_account: dorisws4519115991

  # For terraform reference
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure
  terraform_st_resource_group: amlarc-doris
  terraform_st_storage_account: dorisws4519115991
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
